language: node_js
node_js:
- 8
dist: trusty
sudo: required
script:
- set -e
- serverless config credentials -p aws -n $AWS_PROFILE -k $AWS_ACCESS_KEY -s $AWS_SECRET_KEY
- npm run test
- if [ "$TRAVIS_BRANCH" == "master" ]; then serverless deploy; fi
env:
  global:
  - AWS_PROFILE=inspiration-serverless-test
